### ISSUE TITLE
Build instructions of binary release

### ISSUE THREAD

**Issue by rosterloh** [xiongyihui/CMSIS-DAP#2]
Hey there, I'd love to have a play around with your power profiling changes to CMSIS DAP. Would you mind setting out some instructions for what is needed and how to go about building this project. I am trying to build it for a LPC11U35 interface chip to a NRF51822 target.

Would you mind maybe producing and sharing a binary release?

**Comment by xiongyihui** [comment]
Hello, the power profiling function requires an extra hardware which is a part of our new product - [BLE Smurfs](https://github.com/Seeed-Studio/ble_smurfs). We will release it soon.

**Comment by rosterloh** [comment]
Would you mind giving me some instructions on how you went about building this firmware regardless?  I'd like to develop some of my own changes but I can't seem to find any build instructions for the project. Do you need a Keil licence?

**Comment by xiongyihui** [comment]
The project is built with keil mdk, so keil mdk is required. We can use a lite version (32KB code limitation) which is free of charge. [interface/mdk/lpc11u35](https://github.com/xiongyihui/CMSIS-DAP/tree/master/interface/mdk/lpc11u35) contains keil project file.

**Comment by 594333325** [comment]
你好 我想问一下 Ultrathin 16x32 Red LED Matrix Panel 这个产品是您开发的么？ 我是一个设计学生 正在用这个板子做作品 但是编程上遇到了困难 非常需要帮助。我想要实现通过 摄像头拍摄照片 然后在Max/Msp上面把照片转换成低像素这种 然后通过Arduino再output到led板上面。 
因为目前从网上可以找到这个板子的资料 我不知道在Arduino的代码上要如何实现它能够读取Max/Msp给它的指令 去具体的点亮其中一个pixel。
因为在过去的2周找了很多资料 还是一点头绪都没有。

**Comment by xiongyihui** [comment]
@594333325 
这类问题可以再 http://www.seeedstudio.com/forum/ 上讨论
http://playground.arduino.cc/interfacing/MaxMSP 有介绍 Arduino he MaxMSP通信，
控制 LED Matrix 的一个 Pixel，可以使用 [Ultrathin_LED_Matrix](https://github.com/Seeed-Studio/Ultrathin_LED_Matrix) 库， 调用 drawPoint()

**Comment by 594333325** [comment]
谢谢！！ 我会看一下的感谢感谢

Date: Thu, 22 Jan 2015 18:16:35 -0800

**Comment by rosterloh** [comment]
Hi Yihui,
As the BLE Smurf has been released now I was wanting to have a look at this again. If I build your power_profiling branch with the lpc11u35_nrf51822_if_power_profiling configuration selected I get a whole bunch of link errors. 

```
.\Obj\lpc11u35_nrf51822_if_mbed.axf: Error: L6406E: No space in execution regions with .ANY selector matching board.o(.data).
.\Obj\lpc11u35_nrf51822_if_mbed.axf: Error: L6406E: No space in execution regions with .ANY selector matching usbd_user_cdc_acm.o(.data).
.\Obj\lpc11u35_nrf51822_if_mbed.axf: Error: L6406E: No space in execution regions with .ANY selector matching uart.o(.data).
.\Obj\lpc11u35_nrf51822_if_mbed.axf: Error: L6406E: No space in execution regions with .ANY selector matching swd_host.o(.data).
.\Obj\lpc11u35_nrf51822_if_mbed.axf: Error: L6406E: No space in execution regions with .ANY selector matching usb_config.o(.data).
.\Obj\lpc11u35_nrf51822_if_mbed.axf: Error: L6406E: No space in execution regions with .ANY selector matching serial.o(.data).
.\Obj\lpc11u35_nrf51822_if_mbed.axf: Error: L6406E: No space in execution regions with .ANY selector matching gpio.o(.data).
.\Obj\lpc11u35_nrf51822_if_mbed.axf: Error: L6406E: No space in execution regions with .ANY selector matching rt_system.o(.data).
.\Obj\lpc11u35_nrf51822_if_mbed.axf: Error: L6406E: No space in execution regions with .ANY selector matching rt_task.o(.data).
.\Obj\lpc11u35_nrf51822_if_mbed.axf: Error: L6406E: No space in execution regions with .ANY selector matching rt_timer.o(.data).
.\Obj\lpc11u35_nrf51822_if_mbed.axf: Error: L6406E: No space in execution regions with .ANY selector matching rtx_config.o(.data).
.\Obj\lpc11u35_nrf51822_if_mbed.axf: Error: L6406E: No space in execution regions with .ANY selector matching usb_config.o(.data).
.\Obj\lpc11u35_nrf51822_if_mbed.axf: Error: L6406E: No space in execution regions with .ANY selector matching usb_config.o(.data).
.\Obj\lpc11u35_nrf51822_if_mbed.axf: Error: L6406E: No space in execution regions with .ANY selector matching read_uid.o(.data).
.\Obj\lpc11u35_nrf51822_if_mbed.axf: Error: L6406E: No space in execution regions with .ANY selector matching usbd_lpc11uxx.o(.data).
.\Obj\lpc11u35_nrf51822_if_mbed.axf: Error: L6406E: No space in execution regions with .ANY selector matching usbd_core.o(.data).
.\Obj\lpc11u35_nrf51822_if_mbed.axf: Error: L6406E: No space in execution regions with .ANY selector matching usbd_msc.o(.data).
.\Obj\lpc11u35_nrf51822_if_mbed.axf: Error: L6406E: No space in execution regions with .ANY selector matching rt_time.o(.data).
.\Obj\lpc11u35_nrf51822_if_mbed.axf: Error: L6406E: No space in execution regions with .ANY selector matching usb_config.o(.data).
.\Obj\lpc11u35_nrf51822_if_mbed.axf: Error: L6406E: No space in execution regions with .ANY selector matching usb_config.o(.data).
.\Obj\lpc11u35_nrf51822_if_mbed.axf: Error: L6406E: No space in execution regions with .ANY selector matching dap.o(.data).
.\Obj\lpc11u35_nrf51822_if_mbed.axf: Error: L6406E: No space in execution regions with .ANY selector matching usb_config.o(.data).
.\Obj\lpc11u35_nrf51822_if_mbed.axf: Error: L6406E: No space in execution regions with .ANY selector matching usb_config.o(.data).
.\Obj\lpc11u35_nrf51822_if_mbed.axf: Error: L6406E: No space in execution regions with .ANY selector matching usb_config.o(.data).
.\Obj\lpc11u35_nrf51822_if_mbed.axf: Error: L6407E: Sections of aggregate size 0x98 bytes could not fit into .ANY selector(s).
```

Is there something else needed to build this?

**Comment by xiongyihui** [comment]
I will check the branch next week.
It's a problem that there is not enough RAM. There is a discussion - https://github.com/mbedmicro/CMSIS-DAP/issues/82#issuecomment-72156175

**Comment by rosterloh** [comment]
Thanks. I've managed to get it to compile now but haven't got it running successfully. Checked the pin configs and everything and that's all fine. Have you been using the concat.py utility in the tools folder?

```
python concat.py -i LPC11U35 -t NRF51822
```

Or do you run this without the bootloader? Do you have any plans to integrate all the changes going on in @sg- 's fs_patch [branch](https://github.com/sg-/CMSIS-DAP/tree/fs_patch) ?
